#Basics of R
#firstly, know you questionnaire before data analysis
##first step is to clean the dataset
install.packages("DAAG")
library(DAAG)
##a sequence 1:10 for example will be automatically considered a vector
##is.numerical() function to check if a vector is numerical
##as.numeric function used to convert non-numeric vector into numeric vector
##as.character to convert vector into character
##class() to check type whether numeric or character
##numeric(n) gives n no. of zeroes as a vector
##indexing in r starts from 1 rather than 0
##character> float > integer or numeric
##Extract elements from list by using $ or [[]]
##sample(1:100, size=10) will give 10 random numbers b/w 1 and 100
##set.seed(50) will give the same specific numbers generated by set when set() executed again
## ls() lists the object we have in our environment
##getwd() to get working directory
##write.table() saves dataframe as table  file
##read.table()) can be used to read the dataframe file
##names() used to get column names
##plot( Carbon ~ Year) Carbon on Y axis, Year on X axis
##write.table() to save the dataframe file in working directory
## rm() used to delete things fromr enivironment only and if rm() used in terminal will definetely remove file completely
## ls() used to list the objects/variables
## $ symbol used to select a column from a database
## summary() used to statistical measures of each column individually
## to find Max/Min from range(fossilfuel$carbon)[2] finds Max and replacing [1] in place of [2] gives Min
## nchar() to find no. of characters
## In ecotrix, since we assume in OLS that errors have normal distribution, we check if it's true by using histogram


Year <- c(1800,1850, 1900, 1950, 2000)
Carbon <- c(8, 54, 534, 1630, 6611)
plot(Carbon ~ Year, pch=14) # Carbon will be on y-axis & Year will be on x-axis
#The Plot() function interprets this formula to mean "Plot Carbon as a function of year" or
# "Plot Carbon on the y-axis against Year on the x-axis"
getwd()
## The Working directory is location where R saves files
fossilfuel <- data.frame(year=Year, carbon=Carbon)
fossilfuel
write.table(fossilfuel, file="fuel.txt") #to save table
fossilfuel
rm(fossilfuel) #This will only remove fossilfuel from R environment, to delete file use this code in terminal
fossilfuel
# shows list of objects
ls() 
fossilfuel<- read.table("fuel.txt", header=TRUE )
fossilfuel
summary(fossilfuel) ##statistical measures for each column seperately
names(fossilfuel) ##to get column names
fossilfuel$carbon

fourcities<-c("Toronto", "Canberra", "New York", "London")
sort(fourcities)
nchar("Toronto") ## no. of characters
nchar(fourcities[1])
nchar(fourcities)[1]
summary(cars) ##cars is already existing dataset in R
cars
hist(cars$speed) #makes histogram of speed column of car dataset


##Syntax: dataframe_name[row, column, grouping]
fossilfuel[,2] ##gives 2nd column
##alternatively you can use column name
fossilfuel[,"carbon"]
fossilfuel["carbon", ]
fossilfuel[,] ##we'll get all rows and all columns
fossilfuel[1:3,1] ##rows from 1st to 3rd and 1st column only

#Logical Operators



##set.seed()
#internally, FALSE=0, TRUE=1
## == Operator
a==b
is.vector(a==b) ##will be true iff entire vector is same
c=c(1,2,3,5,7,10)
d=c(11,3,4,5,9,10)
c==d
c!=d
!(c!=d) ##same as c==d
# < > are also logical operators
b<- c>mean(c) 
b ## we're getting TRUE FALSE as < > are logical operators outside []


# Factors in R
# syntax: xf<- factor(x, labels=mylabels)
#how was your day? good-1, okay-2, bad-3
x<- c(3,2,2,3,1,2,3,2,1,2)
xf<- factor(x, labels= c("good","okay","bad")) #ordered=TRUE vs ordered=FALSE
xf

#Naming and indexing vectors

# To use already existing datasets: library(DAAG) & install.packages("DAAG")
install.packages("DAAG")
library(DAAG)

# log can be used when we normality no more  being satisfied and when we want to plot Growth

install.packages("ggplot2")
library(ggplot2)
houseprices
typeof(houseprices$area)
orings



# Ch-1 of book from Q1 to Q15
#Q1:
df= data.frame( area=c(694,905,802,1366,716,963,821,714,1018,887,790,696,771,1006,1191), 
                sale.price=c(192.0,215.0,215.0, 274.0, 112.7, 185.0, 212.0, 220.0, 276.0, 260.0, 221.5, 225.0, 260.0, 293.0, 375.0)
                )
df

#a
plot(data=df, x=df$area, y= df$sale.price)

# Alternative
plot( df$area ~ df$sale.price)

#b
hist(x=df$sale.price)

#c
log_sale.price= log(df$sale.price)
plot(data=df, x=df$area, y=log_sale.price)
hist(x=log_sale.price)

#e: Create a new dataframe by extract rows 1,2,4,11,13 and create new dataframe
df_new <- df[c(1,2,4,11,13), ]
df_new

#Ans 2
orings
new_orings<- orings[c(1,2,4,11,13,18), ]
new_orings
plot(new_orings$Total ~ new_orings$Temperature)

# Houseprice

#create a new df which has all the columns of houseprices2 and sqaure of sale.price
houseprices
sp<- houseprices$sale.price
houseprices2= data.frame( area= houseprices$area, bedrooms=houseprices$bedrooms, 
                          sale.price=houseprices$sale.price, square_of_sale.price=sp^2)
houseprices2
length(houseprices2) #to find no. of columns
length(houseprices2$area) #to find no. of rows

#Extract those rows where bedroom >=5
hf= subset(houseprices2, houseprices2[ ,2]>=5)
hf

View(houseprices2) #to view data


#Ans 3
possum
#a
str(possum) ##str() works like summary()
#b)
complete.cases(possum)



#Ans 4
ais
#a)
str(ais)
#b)

#Ans 5
install.packages('dplyr')
library(dplyr)
is.na(rainforest$branch)

rainforest

#Ans 6
Manitoba.lakes
plot(log2(Manitoba.lakes$area) ~ Manitoba.lakes$elevation)  


                                         
#### 30th January Class ####

install.packages('ISLR')
install.pakages('DAAG')
library(ISLR)
library(DAAG)

df= read.csv("C:/Users/98686/Downloads/CPS1985.csv", header=TRUE)
df
summary(df)
ncol(df) #to check no. of columns
#factor dtype is used for categorical varb

##dummy_col() to convert column into factor data type
is.factor(df$region) ##Region column ain't a factor, but documentataion saying it is
df$region<- as.factor(df$region) #convert dtype of region col to factor
is.factor(df$region)

possum
##if there's null values in col, then it can't be of factor dtype
is.factor(possum$site)
is.factor(possum$sex)
##table() 
tab1<- table(possum$sex) 
tab1
##prop.table()  for proportion/percentage
tab2<- prop.table(tab1)
tab2
##coming back to our imported csv 
tab<- table(df$gender)
tab

Auto
plot(Auto$horsepower ~ Auto$mpg)

iris #already existing r dataset
plot(iris$Species, iris$Sepal.Length)
identify(iris$Species, iris$Sepal.Length)
#after plot() & identify(), point the cursor at the outlier in graph
tab1<- table(possum$sex)
tab2<- prop.table(tab1)
tab2
barplot(tab2, xlab="gender", ylab="proportion", main="possum", names.arg=c("Female","Male"))


####### 2nd Feb Class ####
milk #dataset in DAAG library
colnames(milk)
plot(milk$four, milk$one)
?milk


# lm(): to run regression
plot(milk$four ~ milk$one)
abline(h=mean(milk$one), color='red', lty=2) 
abline(v=mean(milk$four), color='blue',lty=2)
reg<- lm(one~four, data=milk)
plot(reg)

#tip: if d1 & d2 imported dataset and d3 is megred result of d1&d2, so you can delete d1,d2 from Rscript's memory
jobs #dataset in DAAG package
?jobs #to know the dataset meaning



?cor 
cor(jobs) 
jobs2<- jobs[,-7]
jobs2
colnames(jobs2)
cor(jobs2)



install.packages('corrplot')
library(corrplot)

mtcars
######   09 February 2024 #############
install.packages('ggplot2')
library(ggplot2)
##syntax: ggplot()
##ggplot only works for 2D graphs and not 1D (like histogram) or 3D graphs
ggplot(mtcars) #this is our empty graph book
ggplot(mtcars, mapping=aes(x=mpg, y=hp)) #now axis appear
# alternatively: 
ggplot(mtcars)+aes(x=mpg, y=hp)
# to make scatter plot
ggplot(mtcars, mapping=aes(x=mpg, y=hp)) + geom_point()
?faithful #another dataset
ggplot(faithful, mapping=aes(x=eruptions, y=waiting))+geom_point()


#alternatively
ggplot(faithful)+aes(x=eruptions, y=waiting)+geom_point()

ggplot(faithful)+aes(x=eruptions, y=waiting)+geom_point()+geom_area()

ggplot(faithful)+aes(x=eruptions, y=waiting)+geom_point()+geom_area()+geom_boxplot()

ggplot(faithful, mapping= aes(x=eruptions, y=waiting, colour=eruptions<3))+ geom_point()       




diamonds #another dataset
?diamonds
typeof(diamonds$clarity) #returning dtype as integer, but it's a factor, so we use class() to check the dtype
class(diamonds$clarity)
levels(diamonds$clarity)
levels(diamonds$cut)
ggplot(diamonds, aes(x=carat, y=price, colour=clarity)) + geom_point() 
ggplot(diamonds, aes(x=carat, y=price, colour=clarity)) + geom_point() + theme_minimal()


ggplot(diamonds, aes(x=carat, y=price, colour=clarity))+ geom_point() + labs(title="Scatter plot", x="Carat", y="Price in $")

?diamonds #the clarity column has levels ordered from diamond quality worst to best

ggplot(diamonds, aes(x=carat, y=price, colour=clarity)) + geom_point() + scale_color_brewer(palette = "RuRb")+ theme_minimal()








############# 20th February 2023 ##########
library(dplyr)
wages_df<- read.csv('C:/Users/98686/Downloads/CPS1985.csv')
wages_df

d1<- wages_df %>% filter(region=='south', ethnicity=='cauc')
d1 %>% arrange(desc(age))
#slice()
wages_df %>% slice(5:10) #slice() takes subset of rows based on their indexing
#slice_head()
wages_df %>% slice_head(prop=0.5)
?filter
?select
#slice_tail()
#slice_sample()
#slice_min()
#slice_max()
#summarise()
wages_df %>% summarise(age_mean = mean(age, na.rm = TRUE)) # na.rm=TRUE, used to exclude the NA or null values when calculating mean
#group_by()
?group_by
#Combining Multiple functions using pipes: df %>% function1() %>% function2() %>% function3
wages_df
wages_df %>% group_by(sector) %>% select(wage) %>% filter(experience==9) %>% summarise(avg_wage=mean(wage, na.rom=TRUE))
#select() function used to select only one or more columns out of a dataframe









####################################### 23 Feb 2023 ###################################################

?curve
curve(dnorm, from=-3, to=3) #dnorm finds PDF of every sample point
#dnorm:Normal Distribution #we see a Normal Distribution curve
dnorm(x,mean=0,sd=1)
?dt
curve(dt(x,10),from=-3,to=3, col='red',add='TRUE') #dt: t-distribution #dt(x,10) where 10 is degree of freedom

sample<- 50:150
mean_sample<- mean(sample)
sd_sample<- sd(sample)
density<- dnorm(sample, mean_sample, sd_sample)
density
?data.frame
df<- data.frame("iq"=sample, "density"=density)
df
ggplot(df,aes(x=iq,y=density))+geom_point()

# rnorm() gives the specified random no.s having specifed mean and std. devaition
?rnorm
rnorm(10,0,1) 

#rbinom():
rbinom(10,3,0.5)

#pnorm(),pt(),rt(),rnorm(),dnorm(),pvalue()


## dplyr:: select()
















##################### 1st March #####################

library(MASS)
birthwt<-as_tibble(MASS::birtwt)

##whenever we use
names(birthwt.t.test)

# ASSIGNMENT 1:
# 1) Pick any dataset with a categorical variable (ensure it's a factor)
# 2) Change value of the categorical variable ( for example if in data, 1 is Male, 2 is Female and you want to convert 1 to "Male", 2 to "Female" using recode_factor() function)
# 3) Plot means of both groups (use boxplots)(suppose if output is food expenditure, then food exp for male and female seperately)
# 4) Summary Statistics(Max & Min)
# 5) Give Confidence Interval for estimate of means of both variables


########################## 05 March 2024 #################################




# Assignment 2:
# 1) Take any built-in dataset and run regression
# 2) Plot a scatterplot of Y & X
# 3) Extract the residuals & coefficients
# 4) Change the specification to add a polynomial (Example: Y~X  , Y~X+X^2)
# 5) Add an interaction effect (Example: X1+X2+(X1.X2)



########################### 06 March 2024: Normality of Residuals ##################################

# Outlier: If you have extremely large Predicted Y values(i.e, Y hat), then it's oultier

# Stochastic Error: Unpredictable Error i.e, Random Error

# If an error is not random, then it should be included in the model

# The residuals should be mostly around the mean line, for a model to be fit

# To check if residuals are identically distributed, we use either histogram(where we plot residuals) or QQ Plot

# To check if there's any linear relationship b/w 2 variables(say, X & Y), then Scatter Plot can tell

# AutoCorrelation has Time components but MultiCollinearity doesn't has Time Component. 




############ 26th March: Multicollinearity ################
# it's a good practice storing lm object in Y.lm (where Y is dependent variable)
# pairs() is used to create scatterplot matrix

# Multicollinearity
library(ggplot2)
library(corrplot)



# Reading the data
dat_1 <- read.csv('https://online.stat.psu.edu/stat462/sites/onlinecourses.science.psu.edu.stat462/files/data/bloodpress/index.txt')
dat_1 <- read.table('https://online.stat.psu.edu/stat462/sites/onlinecourses.science.psu.edu.stat462/files/data/bloodpress/index.txt')



# the above code returns dat_1 as having V1, V2, etc.. as headers rather than 1st row, so to use 1st row as header use parameter header=TRUE :
dat_1 <- read.table('https://online.stat.psu.edu/stat462/sites/onlinecourses.science.psu.edu.stat462/files/data/bloodpress/index.txt', header=TRUE)
dat_1
summary(dat_1)



#Basics
BP.lm <- lm(BP ~ Weight + Stress, dat_1)
BP.lm
summary(BP.lm) # for quick glance we can use BP.lm , but for more details use summary(BP.lm)



# aov: Analysis of variance
BP.aov <- aov(BP ~ Weight + Stress, dat_1) #BP.aov() has more
summary(BP.aov)
BP.lm
summary(BP.lm) #to get ANOVA results









# intervals of coefficients
# confint(): gives confidence interval
confint(BP.lm)
confint(BP.lm, level=0.99)



# MULTICOLLINEARITY

# interested in determining if a realtionship exist b/w blood pressure and age, weight, body surface area, pulse rate and/or

pairs(dat_1[,2:5], pch=16) 


pairs(dat_1[,c(2,6:8)], pch=1, lower.panel=NULL)
help(pairs)
?pchisq
pairs(dat_1, pch=1, lower.panel=NULL) 




cormat <- cor(dat_1) 
cormat 

corrplot(cormat, type="upper", order="hclust",
         tl.col="black", tl.srt=45) 
corrplot(cormat, method="number", type="lower", order="hclust",
         tl.col="black", tl.srt=45)



# what if i want both?
install.packages("GGally")
library(GGally)





# ggpairs(), i.e, Scatter_Matrix won't come in exam
Scatter_Matrix<- ggpairs(dat_1, columns=c(2:5),
                         title="Scatter Plot Matrix for BP Dataset",
                         axisLabels="show") 
ggsave("Scatter plot matrix.png", Scatter_Matrix, width=7,
       height=7, units="in")
Scatter_Matrix



#################### 02 April 2024 ###################################
# Binomial: when 2 outcomes/ categories of Y feature
# Multinomial: When more than 2 outcomes/categories of Y feature
# Logic vs probit vs 
# 
dat_1 <- read.table('https://online.stat.psu.edu/stat462/sites/onlinecourses.science.psu.edu.stat462/files/data/bloodpress/index.txt', header=TRUE)
dat_1






############### 09th April 2024 ############################################
install.packages("DAAG")
install.packages("estimatr")
library(DAAG)
sugar
class(sugar$weight)
class(sugar$trt) #It's a factor variable(i.e, Categorical Variable)
levels(sugar$trt) #as we can see, 4 unique categories
sugar.aov <- aov(weight ~ trt, data= sugar)
sugar.aov
summary(sugar.aov)
model.matrix(sugar.aov)  
summary.lm(sugar.aov) 







sugar$trt <- factor(sugar$trt, levels=c('A', 'Control','B','C'))
sugar$trt #now the aov
levels(sugar$trt)
sugar.aov <- aov(weight ~ trt, data= sugar)
summary.lm(sugar.aov) 
model.matrix(sugar.aov) 






library(ggplot2) #always import ggplot 2 library wheenver we need ggplot2
library(tidyverse) 
#Creating Scatter Plot:
p<- mtcars %>% ggplot(aes(x=hp,y=mpg))+geom_point()+labs(y="Mile per Gallon",x="Horse Power", title="Scatter Diagram")+theme(plot.title=element_text(hjust=0.5))
p 
mtcars
mpg <- mtcars %>% lm(mpg ~ hp+ I(hp^2))
p + geom_smooth(method = "lm", formula = y ~  x + I(x^2),se=F) #geom_smooth  #Polynomial Regression






library(DAAG)
seedrates
seed.p<- seedrates %>% ggplot(aes(x=rate,y=grain))+geom_point()+labs(y="Grain",x="Rate", title="Scatter Diagram")+theme(plot.title=element_text(hjust=0.5))
seed.p
seed.p + geom_smooth(method = "lm", formula = y ~  x + I(x^2),se=F) + geom_smooth(method = "lm", formula = y ~  x ,se=F, color="Red") 


